// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Minimal.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__MINIMAL_HPP
#define FAST_DDS_GENERATED__MINIMAL_HPP

#include <cstdint>
#include <utility>
#include <vector>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MINIMAL_SOURCE)
#define MINIMAL_DllAPI __declspec( dllexport )
#else
#define MINIMAL_DllAPI __declspec( dllimport )
#endif // MINIMAL_SOURCE
#else
#define MINIMAL_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MINIMAL_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure Minimal defined by the user in the IDL file.
 * @ingroup Minimal
 */
class Minimal
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Minimal()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Minimal()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Minimal that will be copied.
     */
    eProsima_user_DllExport Minimal(
            const Minimal& x)
    {
                    m_index = x.m_index;

                    m_time_stamp = x.m_time_stamp;

                    m_img_data = x.m_img_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Minimal that will be copied.
     */
    eProsima_user_DllExport Minimal(
            Minimal&& x) noexcept
    {
        m_index = x.m_index;
        m_time_stamp = x.m_time_stamp;
        m_img_data = std::move(x.m_img_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Minimal that will be copied.
     */
    eProsima_user_DllExport Minimal& operator =(
            const Minimal& x)
    {

                    m_index = x.m_index;

                    m_time_stamp = x.m_time_stamp;

                    m_img_data = x.m_img_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Minimal that will be copied.
     */
    eProsima_user_DllExport Minimal& operator =(
            Minimal&& x) noexcept
    {

        m_index = x.m_index;
        m_time_stamp = x.m_time_stamp;
        m_img_data = std::move(x.m_img_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Minimal object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Minimal& x) const
    {
        return (m_index == x.m_index &&
           m_time_stamp == x.m_time_stamp &&
           m_img_data == x.m_img_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x Minimal object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Minimal& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(
            uint32_t _index)
    {
        m_index = _index;
    }

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const
    {
        return m_index;
    }

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index()
    {
        return m_index;
    }


    /*!
     * @brief This function sets a value in member time_stamp
     * @param _time_stamp New value for member time_stamp
     */
    eProsima_user_DllExport void time_stamp(
            uint32_t _time_stamp)
    {
        m_time_stamp = _time_stamp;
    }

    /*!
     * @brief This function returns the value of member time_stamp
     * @return Value of member time_stamp
     */
    eProsima_user_DllExport uint32_t time_stamp() const
    {
        return m_time_stamp;
    }

    /*!
     * @brief This function returns a reference to member time_stamp
     * @return Reference to member time_stamp
     */
    eProsima_user_DllExport uint32_t& time_stamp()
    {
        return m_time_stamp;
    }


    /*!
     * @brief This function copies the value in member img_data
     * @param _img_data New value to be copied in member img_data
     */
    eProsima_user_DllExport void img_data(
            const std::vector<uint8_t>& _img_data)
    {
        m_img_data = _img_data;
    }

    /*!
     * @brief This function moves the value in member img_data
     * @param _img_data New value to be moved in member img_data
     */
    eProsima_user_DllExport void img_data(
            std::vector<uint8_t>&& _img_data)
    {
        m_img_data = std::move(_img_data);
    }

    /*!
     * @brief This function returns a constant reference to member img_data
     * @return Constant reference to member img_data
     */
    eProsima_user_DllExport const std::vector<uint8_t>& img_data() const
    {
        return m_img_data;
    }

    /*!
     * @brief This function returns a reference to member img_data
     * @return Reference to member img_data
     */
    eProsima_user_DllExport std::vector<uint8_t>& img_data()
    {
        return m_img_data;
    }



private:

    uint32_t m_index{0};
    uint32_t m_time_stamp{0};
    std::vector<uint8_t> m_img_data;

};

#endif // _FAST_DDS_GENERATED_MINIMAL_HPP_


